### ISSUE TITLE
Issue loading application for the first time

### ISSUE THREAD

**Issue by Willster419** [Willster419/RelhaxModpack#90]
# **Describe the bug**
The user is unable to load the application. The stack trace implies it's the first time because it contains `FirstLoadAcknowledgments`

# **To Reproduce**
I'm not currently able to re-produce

# **Expected behavior**
It's supposed to work. Well, at least not crash.

# **Screenshots**

# **PC info (please complete the following information):**
 - OS: Windows 7 Service Pack 1

# **Modpack Version**
- 1.1.1.0

# **Logs (Required)**
[log_snipit.txt](https://github.com/Willster419/RelhaxModpack/files/4945025/log_snipit.txt)

**Additional context**
This person contacted me via email. I'm opening this on his behalf.

**Comment by Willster419** [comment]
Replied to the user:

> Take a look at this download page and click "download the .net framework 4.8 runtime"

> https://dotnet.microsoft.com/download/dotnet-framework/net48

> also, i'd check your system using sfc:

> https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system

Note, this is similar to another user's issue (Windows 7): http://forum.worldoftanks.eu/index.php?/topic/623269-1912-the-relhax-modpack-omc-20-fastest-mods-installer-with-previews/page__st__1100__pid__17964200#entry17964200

**Comment by SHADOW2607** [comment]
Well I downloaded/installed  the .net framework 4.8 runtime  and checked my system using sfc.  No problems were dectected so I tried to install the modpak again with the same results

**Comment by Willster419** [comment]
Please try this custom build and see if it works. I've added some runtime properties as recommended by Microsoft.
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element
[RelhaxModpack.zip](https://github.com/Willster419/RelhaxModpack/files/4951321/RelhaxModpack.zip)

**Comment by SHADOW2607** [comment]
I tried that as well.  Same results

**Comment by Willster419** [comment]
Until i can get more information (because i can't reproduce), I need to ask you to run test builds to get what I need.
Please try this build. It will write a lot of logging information to `relhax.log` I need that file to get some information about your CLR and .net runtime.

Just to double check, you are running windows 7 (Home premium)?

[RelhaxModpack.zip](https://github.com/Willster419/RelhaxModpack/files/4954555/RelhaxModpack.zip)

**Comment by SHADOW2607** [comment]
Yes, I am running windows 7 (home premium)

**Comment by SHADOW2607** [comment]
same as before..  Log and exception capture display below..


[Relhax.log](https://github.com/Willster419/RelhaxModpack/files/4965922/Relhax.log)
--

System.Windows.Markup.XamlParseException: Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception. ---> System.InvalidOperationException: Property path is not valid. 'FrameworkAppContextSwitches' does not have a public property named 'UseLegacyAccessibilityFeatures'.
   at System.Windows.PropertyPath.ResolvePropertyName(String name, Object item, Type ownerType, Object context, Boolean throwOnError)
   at System.Windows.PropertyPath.ResolvePathParts(ITypeDescriptorContext typeDescriptorContext)
   at System.Windows.PropertyPath..ctor(String path, ITypeDescriptorContext typeDescriptorContext)
   at System.Windows.PropertyPathConverter.ConvertFrom(ITypeDescriptorContext typeDescriptorContext, CultureInfo cultureInfo, Object source)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at RelhaxModpack.Windows.FirstLoadAcknowledgments.InitializeComponent()
   at RelhaxModpack.Windows.FirstLoadAcknowledgments..ctor()
   at RelhaxModpack.MainWindow.<TheMainWindow_Loaded>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Willster419** [comment]
Thanks for the log info. It gave me some important information.

In the log file, line 16 is the most important. It tells me the release number of the .NET Framework version you have installed. Here's the snipit from your log:
`2020-07-23 07:42:03.054   DEBUG: Registry: Subkey=Release, Value=461814`

This does not match the release key from my computer(s), developer and my windows 7 VM. From my log:
`2020-07-21 08:36:55.073   DEBUG: Registry: Subkey=Release, Value=528040`

And according to this microsoft documentation:
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#detect-net-framework-45-and-later-versions

This tells me that the latest .NET framework you currently have installed is *4.7.2*, not *4.8*.

I'll admit, it may not be the root cause of the issue, but it is certainly something that should be fixed before we continue diagnosing the issue. You need to be running the same .NET framework runtime that the application targets.

After you install .net framework 4.8, you can always run the application again and check that number to verify that it is installed successfully. Or, if you are familiar with `regedit`, you can use that.

**Comment by SHADOW2607** [comment]
That was it, I removed 4.8 .NET framework and reinstalled it and now your modpak WORKS!!! Thank you so much for your time.

**Comment by Willster419** [comment]
You are welcome!

An action item I will take from this is to check the .NET framework at runtime and display a warning to the user.
I'll keep this issue open until I make that PR.
